### ISSUE TITLE
Feature request: Add support for layouts and categories

### ISSUE THREAD

**Issue by JesseTG** [Valax321/RewiredInspectorProperty#1]
Hi there. Is it possible you could add support for displaying other Rewired data structures like categories or layouts? I can submit a PR if necessary.

**Comment by Valax321** [comment]
I'll look into it! Categories should be pretty simple but the structure for layouts is a bit different to the other data.

**Comment by JesseTG** [comment]
Thank you!

> the structure for layouts is a bit different to the other data

How so?

**Comment by Valax321** [comment]
I just pushed a new commit (https://github.com/Valax321/RewiredInspectorProperty/commit/de90b1ddd5bf05233c5be48e41e444127edcb332) that adds new types for the map categories (`RewiredMapCategory`) and layouts (`RewiredMouseLayout`, `RewiredKeyboardLayout` etc.). I'm not too familiar with the more advanced stuff in Rewired with the layout rules and custom controllers and such, so I haven't implemented anything for them yet.

Layouts use nested classes which I thought might cause issues with my class lookup code but it ended up supporting it already.

**Comment by JesseTG** [comment]
Thank you. I'll give this a try and report back on how it works. In the meantime, can you tag your latest commit so it'll show up on [OpenUPM](https://openupm.com/packages/com.valax321.rewiredinspectorproperty/)?

**Comment by Valax321** [comment]
All done
